runtime: go112

handlers:
- url: /portfolio
  static_dir: portfolio

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

# Use HTTPS for all requests.
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
