runtime: go
api_version: go1

handlers:
  - url: /$
    script: _go_app

  - url: /portfolio
    static_dir: portfolio

  - url: /favicon.ico
    static_files: favicon.ico
    upload: favicon.ico

skip_files:
  - /portfolio/*.md


